services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: guidebook
      POSTGRES_DB: guidebook
    volumes:
      - lms-db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
  app:
    build:
      context: .
      dockerfile: api.Dockerfile
    env_file:
      - .env.e2e
    ports:
      - 3000:3000
    depends_on:
      - db
  migrate:
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:guidebook@db:5432/guidebook?sslmode=disable
    command: migrate
    depends_on:
      - db
  seed:
    build:
      context: .
      dockerfile: api.Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:guidebook@db:5432/guidebook?sslmode=disable
    command: seed
    depends_on:
      - db

volumes:
  lms-db-data:
    driver: local
