name: PRODUCTION - Deploy ADMIN

env:
  HUSKY: 0

on:
  push:
    branches:
      - "deploy-production/**"
    paths:
      - apps/admin/**
      - .github/workflows/deploy-admin-production.yml

jobs:
  build-admin:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.PRD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PRD_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.PRD_AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ secrets.PRD_AWS_ECR_REGISTRY_ADMIN }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -f ./admin.Dockerfile --build-arg VERSION=$IMAGE_TAG -t $ECR_REGISTRY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY:$IMAGE_TAG $ECR_REGISTRY:latest
          docker push $ECR_REGISTRY:$IMAGE_TAG
          docker push $ECR_REGISTRY:latest

      - name: Install Selleo CLI
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with:
          repo: selleo/cli
          tag: v0.26.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ECS Deployment
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          ECS_CLUSTER: ${{ vars.AWS_ECS_CLUSTER }}
          ECS_SERVICE: ${{ vars.AWS_ECS_SERVICE_ADMIN }}
          DOCKER_IMAGE: ${{ secrets.AWS_ECR_REGISTRY_ADMIN }}:${{ github.sha }}
        run: selleo aws ecs deploy --region $AWS_REGION --cluster $ECS_CLUSTER --service $ECS_SERVICE --docker-image $DOCKER_IMAGE