# uncomment when staging will be ready

# name: Nightly Playwright Tests

# on:
#   schedule:
#     - cron: "0 1 * * *"
#   workflow_dispatch:

# jobs:
#   playwright:
#     name: Playwright Tests
#     runs-on: ubuntu-latest
#     container:
#       image: mcr.microsoft.com/playwright:v1.45.3-jammy
#     defaults:
#       run:
#         working-directory: ./apps/web/
#     steps:
#       - uses: actions/checkout@v4
#       - uses: pnpm/action-setup@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20.15.0
#       - name: Install dependencies
#         run: pnpm install
#       - name: Run your tests
#         run: pnpm playwright test
#         env:
#           HOME: /root
