name: E2E - Playwright Tests

env:
  HUSKY: 0

on:
  workflow_run:
    workflows:
      - "STAGING - Deploy API"
    types:
      - completed
  workflow_call:

jobs:
  playwright:
    name: Playwright Tests
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' ||
      github.event_name == 'workflow_call'
    defaults:
      run:
        working-directory: ./apps/web/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.15.0
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm playwright test
        env:
          HOME: /root
          TEST_KEY: ${{ secrets.TEST_KEY }}
